ruimsig:
  hosts:
    ruimsigPrint1:
      ansible_host: ruimsigPrint1
clearwater:
  hosts:
    clearwaterPrint1:
      ansible_host: clearwaterPrint1
biden:
  hosts:
    bidenPrint1:
      ansible_host: bidenPrint1

current:
  hosts:
    bidenPrint1:
      ansible_host: bidenPrint1
