ruimsig:
  hosts:
    ruimsigPrint1:
      ansible_host: ruimsigPrint1
clearwater:
  hosts:
    clearwaterPrint1:
      ansible_host: clearwaterPrint1

current:
  hosts:
    clearwaterPrint1:
      ansible_host: clearwaterPrint1
