---
- hosts: current
  gather_facts: yes
  name: PrintService
  roles:
    # - ssh
    # - update
    # - geerlingguy.pip
    # - role: geerlingguy.docker
    #   docker_users:
    #     - doink
    # - tailscale
    - compose
  become: yes
