---
- name: Debian | Add Tailscale Signing Key
  become: true
  ansible.builtin.get_url:
    url: "{{ tailscale_apt_signkey }}"
    dest: "{{ tailscale_apt_keyring_path }}"
    mode: "0644"

- name: Debian | Add Tailscale Deb
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ tailscale_apt_deb }}"
    filename: "tailscale"
    state: present

- name: Debian | Install Tailscale
  become: true
  ansible.builtin.apt:
    name: "{{ tailscale_package }}"
    cache_valid_time: 3600
    state: present
