---
- name: Setup Wifi Home
  ansible.builtin.template:
    src: templates/home.nmconnection.j2
    dest: "{{ home_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Setup Wifi Phone
  ansible.builtin.template:
    src: templates/phone.nmconnection.j2
    dest: "{{ phone_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Setup Wifi Clearwater
  ansible.builtin.template:
    src: templates/clearwater.nmconnection.j2
    dest: "{{ clearwater_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Setup Wifi Ruimsig
  ansible.builtin.template:
    src: templates/ruimsig.nmconnection.j2
    dest: "{{ ruimsig_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Setup Wifi Biden
  ansible.builtin.template:
    src: templates/biden.nmconnection.j2
    dest: "{{ biden_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Setup Wifi Cirqlar
  ansible.builtin.template:
    src: templates/cirqlar.nmconnection.j2
    dest: "{{ cirqlar_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Setup Wifi Presto
  ansible.builtin.template:
    src: templates/presto.nmconnection.j2
    dest: "{{ presto_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Setup Wifi Presto New
  ansible.builtin.template:
    src: templates/prestonew.nmconnection.j2
    dest: "{{ prestonew_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Setup Wifi Krook and King
  ansible.builtin.template:
    src: templates/krookandking.nmconnection.j2
    dest: "{{ krookandking_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Reload Wifi Config
  ansible.builtin.command: sudo nmcli connection reload
